title: Jiaxin Huang's Homepage
page-top-title: Jiaxin Huang
top-section-bg-text: Robot Engineering
home-subtitle: Jiaxin Huang&ensp;|&ensp;黄嘉昕
copyright-text: '&copy; Jiaxin Huang 2023-2024. All Rights Reserved.'
